version: "3"
services:
  storage:
    build: ./localperfdata
    ports:
      - 8080:8080
  perf:
    build: ./localperf
    entrypoint:
      - localperf
      - "-addr=:8080"
    ports:
      - 8088:8080